/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './resources/**/*.blade.php',
        './resources/**/*.js',
        './resources/**/*.vue',
    ],
    theme: {
        extend: {
            colors: {
                'on-error': '#ffffff',
                'tertiary-fixed': '#ffdbcd',
                'on-primary-fixed': '#00174b',
                'surface-variant': '#e0e3e5',
                'primary-fixed': '#dbe1ff',
                'tertiary-container': '#bc4800',
                outline: '#737686',
                'surface-container-highest': '#e0e3e5',
                'on-tertiary-fixed': '#360f00',
                'on-background': '#191c1e',
                'on-secondary': '#ffffff',
                'surface-container-lowest': '#ffffff',
                'on-tertiary-fixed-variant': '#7d2d00',
                secondary: '#515f74',
                background: '#f7f9fb',
                'on-tertiary-container': '#ffede6',
                'surface-bright': '#f7f9fb',
                'error-container': '#ffdad6',
                'on-tertiary': '#ffffff',
                'on-surface-variant': '#434655',
                surface: '#f7f9fb',
                'primary-fixed-dim': '#b4c5ff',
                'secondary-fixed': '#d5e3fc',
                'on-primary-container': '#eeefff',
                'inverse-primary': '#b4c5ff',
                'on-secondary-fixed-variant': '#3a485b',
                error: '#ba1a1a',
                'on-secondary-container': '#57657a',
                'surface-tint': '#0053db',
                'surface-container-high': '#e6e8ea',
                'inverse-surface': '#2d3133',
                'on-surface': '#191c1e',
                'surface-dim': '#d8dadc',
                'secondary-container': '#d5e3fc',
                'inverse-on-surface': '#eff1f3',
                'surface-container': '#eceef0',
                'secondary-fixed-dim': '#b9c7df',
                'on-secondary-fixed': '#0d1c2e',
                'on-primary': '#ffffff',
                'on-primary-fixed-variant': '#003ea8',
                tertiary: '#943700',
                'tertiary-fixed-dim': '#ffb596',
                primary: '#004ac6',
                'outline-variant': '#c3c6d7',
                'surface-container-low': '#f2f4f6',
                'primary-container': '#2563eb',
                'on-error-container': '#93000a',
                'success-green': {
                    DEFAULT: '#10B981',
                    bg: 'rgba(16, 185, 129, 0.1)',
                    text: '#065F46',
                },
            },
            borderRadius: {
                pill: '16px',
            },
            spacing: {
                xs: '4px',
                sm: '8px',
                md: '16px',
                lg: '24px',
                xl: '40px',
                'margin-mobile': '16px',
                'margin-desktop': '32px',
                gutter: '16px',
            },
            fontFamily: {
                sans: ['Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
            },
            fontSize: {
                'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
                'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
                'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
                'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '500' }],
                'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
            },
            boxShadow: {
                'level-1': '0px 4px 12px rgba(0, 0, 0, 0.05)',
                'level-2': '0px 10px 25px rgba(0, 0, 0, 0.10)',
            },
        },
    },
    plugins: [require('@tailwindcss/forms')],
};
